### PR TITLE
Fix error undefined method merge

### PR DESCRIPTION
**Pull request by taman9333**
* Fix shrine version as bundler get shrine version 3

### CODE REVIEW

**Comment by katafrakt** [comment]
@taman9333 thanks for the pull request. As you see the tests are failing. This is because Gemfile is wrong - it should not contain `gem 'shrine'` line at all as it is handled by gemspec in this case. Would you like to fix your PR or should I do it?

**Comment by taman9333** [comment]
@katafrakt you are right, I've removed it from Gemfile as it's handled to be lower than <3 in gemspec & tests run successfully.

**Comment by katafrakt** [comment]
Thanks again!

**Comment by taman9333** [comment]
Thanks for your quick response   👍  👍

**Pull request merged**
